### ISSUE TITLE
Update types please

### ISSUE THREAD

**Issue by alevinru** [grammyjs/web-app#5]
.showScanQrPopup() and .platform are missing

**Comment by KnorpelSenf** [comment]
This repo only uses the types of another package. We extracted them into `@types/telegram-web-app`. Do you want to contribute to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/telegram-web-app and add the missing types from the Bot API 6.4 update?

**Comment by alevinru** [comment]
> This repo only uses the types of another package. We extracted them into `@types/telegram-web-app`. Do you want to contribute to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/telegram-web-app and add the missing types from the Bot API 6.4 update?

I am not experienced enough in writing ts to contribute

**Comment by KnorpelSenf** [comment]
This was completed in a0dd51239d6266814507b546f72f0dea3d1d2262 and released in 1.3.0.
